=== jonasvanpelt/paparazzi/conf/autopilot/autopilot.dtd
<!-- Paparazzi Autopilot DTD -->

<!ELEMENT autopilot (modules*,control_block*,exceptions?,mode*)>
<!ELEMENT control_block (call*)>
<!ELEMENT exceptions (exception*)>
<!ELEMENT mode (select*,control*,exception*)>
<!ELEMENT select EMPTY>
<!ELEMENT control (call|call_block)*>
<!ELEMENT exception EMPTY>
<!ELEMENT call EMPTY>
<!ELEMENT call_block EMPTY>
<!ELEMENT modules (load)*>
<!ELEMENT load (configure|define)*>
<!ELEMENT define EMPTY>
<!ELEMENT configure EMPTY>

<!ATTLIST autopilot
name CDATA #IMPLIED>

<!ATTLIST control_block
name CDATA #REQUIRED>

<!ATTLIST mode
name CDATA #REQUIRED
start CDATA #IMPLIED
stop CDATA #IMPLIED>

<!ATTLIST exceptions>

<!ATTLIST select
cond CDATA #REQUIRED
exception CDATA #IMPLIED>

<!ATTLIST control
freq CDATA #REQUIRED>

<!ATTLIST exception
cond CDATA #REQUIRED
deroute CDATA #REQUIRED>

<!ATTLIST call
fun CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST call_block
name CDATA #REQUIRED>

<!ATTLIST modules>

<!ATTLIST load
name CDATA #REQUIRED
target CDATA #IMPLIED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #REQUIRED>

=== jonasvanpelt/paparazzi/conf/autopilot/rotorcraft_autopilot.xml
<!DOCTYPE autopilot SYSTEM "autopilot.dtd">

<autopilot name="Booz Quadrotor Autopilot (Basic version)">

  <control_block name="attitude_loop">
    <call fun="SetAttitudeFromRC(rc_values)"/>
    <call fun="AddAttitudeFromFMS()" cond="fms.enabled"/>
    <call fun="booz_stabilization_attitude_run(booz2_autopilot_in_flight)"/>
  </control_block>

  <control_block name="altitude_loop">
    <call fun="SetAltitudeFromFMS()" cond="fms.enabled"/>
    <call fun="b2_gv_update_ref_from_z_sp(booz2_guidance_v_z_sp)"/>
    <call fun="run_hover_loop(booz2_autopilot_in_flight)"/>
    <call fun="SaturateThrottle(rc_values)"/>
  </control_block>

  <exceptions>
    <exception cond="too_far_from_home" deroute="HOME"/>
  </exceptions>

  <mode name="ATTITUDE" start="booz_stabilization_attitude_enter()">
    <select cond="$DEFAULT_MODE"/>
    <select cond="RCMode0()"/>
    <control freq="512">
      <call_block name="attitude_loop"/>
      <call fun="SetThrottleFromRC(rc_values)"/>
      <call fun="actuators_set(booz2_autopilot_motors_on)"/>
    </control>
    <exception cond="RCLost()" deroute="FAILSAFE"/>
  </mode>

  <mode name="VERTICAL" start="booz_stabilization_attitude_enter()|booz_guidance_v_enter()">
    <select cond="RCMode1()"/>
    <control freq="512">
      <call_block name="attitude_loop"/>
      <call_block name="altitude_loop"/>
      <call fun="actuators_set(booz2_autopilot_motors_on)"/>
    </control>
    <exception cond="RCLost()" deroute="FAILSAFE"/>
  </mode>

  <mode name="NAV" start="booz_guidance_h_nav_enter()|booz_guidance_v_enter()">
    <select cond="RCMode2()" exception="HOME"/>
    <select cond="RCMode2() && DLModeNav()"/>
    <control freq="32">
      <call fun="nav_periodic_task()"/>
    </control>
    <control freq="512">
      <call fun="SetCommandFromAP()"/>
      <call fun="GuidanceNavHorizontal()"/>
      <call fun="GuidanceNavVertical()"/>
      <call fun="AddAttitudeFromRC(rc_values)" cond="!RCLost()"/>
      <call fun="booz_stabilization_attitude_run(booz2_autopilot_in_flight)"/>
      <call fun="SaturateThrottle(rc_values)" cond="!RCLost()"/>
      <call fun="actuators_set(booz2_autopilot_motors_on)"/>
      <call_block name="actuators_ap"/>
    </control>
    <exception cond="GPSLost()" deroute="FAILSAFE"/>
  </mode>

  <mode name="HOME" start="booz_guidance_h_nav_enter()|booz_guidance_v_enter()">
    <control freq="32">
      <call fun="nav_home()"/>
    </control>
    <control freq="512">
      <call fun="SetCommandFromAP()"/>
      <call fun="GuidanceNavHorizontal()"/>
      <call fun="GuidanceNavVertical()"/>
      <call fun="booz_stabilization_attitude_run(booz2_autopilot_in_flight)"/>
      <call fun="actuators_set(booz2_autopilot_motors_on)"/>
    </control>
    <exception cond="GPSLost()" deroute="FAILSAFE"/>
  </mode>

  <!-- Safe landing -->
  <mode name="FAILSAFE" start="failsafe_enter()|booz_stabilization_attitude_enter()|booz_guidance_v_enter()" stop="failsafe_exit()">
    <control freq="512">
      <call fun="SetFailsafeCommand()"/>
      <call fun="booz_stabilization_attitude_run(booz2_autopilot_in_flight)"/>
      <call fun="b2_gv_update_ref_from_zd_sp(booz2_guidance_v_zd_sp)"/>
      <call fun="run_hover_loop(booz2_autopilot_in_flight)"/>
      <call fun="actuators_set(booz2_autopilot_motors_on)"/>
    </control>
    <exception cond="!GPSLost()" deroute="$LAST_MODE"/>
  </mode>

</autopilot>

=== jonasvanpelt/paparazzi/conf/autopilot/fixedwing_autopilot.xml
<!DOCTYPE autopilot SYSTEM "autopilot.dtd">

<autopilot name="Fixed Wing Autopilot">

  <!--modules>
    <load name=""/>
  </modules-->

  <control_block name="actuators_ap">
    <call fun="SetCommandsFromAP(commands)"/>
    <call fun="SetActuatorsFromCommands(commands)"/>
  </control_block>

  <control_block name="attitude">
    <call fun="h_ctl_attitude_loop()"/>
    <call fun="h_ctl_throttle_slew()"/>
  </control_block>

  <exceptions>
    <exception cond="too_far_from_home" deroute="HOME"/>
  </exceptions>

  <mode name="MANUAL">
    <select cond="RCMode0()"/>
    <control freq="60">
      <call fun="SetCommandsFromRC(commands, rc_values)"/>
      <call fun="SetActuatorsFromCommands(commands)"/>
    </control>
    <exception cond="RCLost()" deroute="HOME"/>
  </mode>

  <mode name="AUTO1">
    <select cond="RCMode1()"/>
    <control freq="60">
      <call fun="SetAttitudeThrottleFromRC(rc_values)"/>
      <call_block name="attitude"/>
      <call_block name="actuators_ap"/>
    </control>
    <exception cond="RCLost()" deroute="HOME"/>
  </mode>

  <mode name="AUTO2">
    <select cond="$DEFAULT_MODE"/>
    <select cond="RCMode2()" exception="HOME"/>
    <select cond="RCMode2() && DLMode2()"/>
    <control freq="4">
      <call fun="navigation_task()"/>
    </control>
    <control freq="60">
      <call fun="SetApOnlyCommands(commands)"/>
      <call fun="SetAutoCommandsFromRC(commands, rc_values)" cond="!RCLost()"/>
      <call_block name="attitude"/>
      <call_block name="actuators_ap"/>
    </control>
    <exception cond="GPSLost()" deroute="GPS_LOST"/>
  </mode>

  <mode name="HOME">
    <control freq="4">
      <call fun="nav_home()"/>
    </control>
    <control freq="60">
      <call_block name="attitude"/>
      <call_block name="actuators_ap"/>
    </control>
    <exception cond="GPSLost()" deroute="GPS_LOST"/>
  </mode>

  <mode name="GPS_LOST">
    <control freq="4">
      <call fun="nav_gps_lost()"/>
    </control>
    <control freq="60">
      <call_block name="attitude"/>
      <call_block name="actuators_ap"/>
    </control>
    <exception cond="!GPSLost()" deroute="$LAST_MODE"/>
  </mode>

</autopilot>
